name: synk
description: A sample command-line application.
version: 0.1.0-beta.1
publish_to: none
repository: https://github.com/gliscowo/synk

environment:
  sdk: ^3.0.5

dependencies:
  dart_console: ^1.2.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  modrinth_api:
    git:
      url: https://github.com/gliscowo/modrinth_api
      ref: a896d32
  args: ^2.4.2
  crypto: ^3.0.3
  http_parser: ^4.0.2
  github: ^9.17.0
  glob: ^2.1.2
  archive: ^3.3.7
  toml: ^0.15.0
  pub_semver: ^2.1.4
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.21.0
